import { requireAuth } from '@/lib/auth'
import { sql } from '@/lib/db'
import { NextResponse } from 'next/server'

export async function POST(req: Request) {
  try {
    const user = await requireAuth()
    const { documentId } = await req.json()

    // Verify document belongs to user
    const documents = await sql`
      SELECT * FROM documents
      WHERE id = ${documentId} AND user_id = ${user.id}
    `

    if (documents.length === 0) {
      return NextResponse.json(
        { error: 'Document not found' },
        { status: 404 }
      )
    }

    const document = documents[0]

    const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${document.title}</title>
  <style>
    @page {
      margin: 1in;
      size: A4;
    }
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    body {
      font-family: 'Times New Roman', 'Georgia', serif;
      font-size: 12pt;
      line-height: 1.6;
      color: #000;
      max-width: 100%;
      background: white;
      padding: 0;
    }
    .document-container {
      max-width: 8.5in;
      margin: 0 auto;
      padding: 1in;
      background: white;
    }
    .content {
      white-space: pre-wrap;
      text-align: left;
      margin-bottom: 2em;
    }
    .content p {
      margin: 1em 0;
    }
    .content strong {
      font-weight: bold;
    }
    .footer {
      margin-top: 3em;
      padding-top: 1em;
      border-top: 2px solid #e5e7eb;
      font-size: 9pt;
      color: #6b7280;
      text-align: center;
    }
    .watermark {
      position: fixed;
      bottom: 0.5in;
      right: 0.5in;
      font-size: 8pt;
      color: #9ca3af;
      opacity: 0.7;
    }
    @media print {
      body {
        padding: 0;
        margin: 0;
      }
      .no-print {
        display: none;
      }
    }
  </style>
</head>
<body>
  <div class="document-container">
    <div class="content">${document.content.replace(/\n/g, '<br>')}</div>
    <div class="footer">
      <p><strong>Legal Disclaimer:</strong> This document was generated by Letterise and does not constitute legal advice.</p>
      <p>For legal matters, please consult a licensed attorney or solicitor.</p>
      <p style="margin-top: 0.5em; font-size: 8pt;">Generated on ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })} • Letterise.com</p>
    </div>
  </div>
</body>
</html>
    `

    return new NextResponse(html, {
      headers: {
        'Content-Type': 'text/html',
        'Content-Disposition': `attachment; filename="${document.title.replace(/[^a-z0-9]/gi, '_')}.html"`,
      },
    })
  } catch (error: any) {
    console.error('[v0] PDF export error:', error)
    
    if (error.message === 'Unauthorized') {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      )
    }

    return NextResponse.json(
      { error: 'Failed to export document' },
      { status: 500 }
    )
  }
}
