-- Chargeback / Payment Disputes Templates
INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Chargeback (Mastercard/Visa)', 'chargeback-mastercard-visa', 'Request a chargeback for disputed card payments', 
'[{"id":"cardType","label":"Card Type","type":"select","options":["Mastercard","Visa","Amex"],"required":true},{"id":"transactionDate","label":"Transaction Date","type":"date","required":true},{"id":"amount","label":"Transaction Amount","type":"text","required":true},{"id":"merchantName","label":"Merchant Name","type":"text","required":true},{"id":"disputeReason","label":"Reason for Dispute","type":"select","options":["Goods not received","Goods not as described","Goods faulty/damaged","Service not provided","Charged wrong amount","Duplicate charge","Cancelled order but still charged"],"required":true},{"id":"contactAttempts","label":"Contact Attempts with Merchant","type":"textarea","required":true},{"id":"evidence","label":"Evidence Available","type":"textarea","required":true}]',
'You are a professional letter writer helping a customer request a chargeback from their card provider. Write a formal letter to the card company explaining the disputed transaction, the reason for the chargeback request, evidence of the issue, attempts to resolve with the merchant, and formally requesting a chargeback under the card scheme rules. Be clear and factual.'
FROM categories WHERE slug = 'chargeback-disputes';

INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Section 75 Claim', 'section-75-claim', 'Make a claim for purchases over £100 on credit card', 
'[{"id":"cardProvider","label":"Credit Card Provider","type":"text","required":true},{"id":"purchaseDate","label":"Purchase Date","type":"date","required":true},{"id":"amount","label":"Purchase Amount","type":"text","required":true},{"id":"merchantName","label":"Merchant/Retailer Name","type":"text","required":true},{"id":"itemDescription","label":"Item/Service Description","type":"text","required":true},{"id":"issueDescription","label":"Problem Description","type":"textarea","required":true},{"id":"merchantResolution","label":"Merchant Response (if any)","type":"textarea","required":false},{"id":"remedy","label":"Remedy Sought","type":"text","required":true}]',
'You are a professional letter writer helping a customer make a Section 75 claim. Write a formal letter citing Section 75 of the Consumer Credit Act 1974, explaining that the card provider is jointly and severally liable for breach of contract or misrepresentation when goods/services cost £100-£30,000. Clearly describe the breach, previous attempts to resolve, and request the card provider to refund the amount as they share equal liability with the retailer.'
FROM categories WHERE slug = 'chargeback-disputes';

INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Section 75A Claim', 'section-75a-claim', 'Make a claim for purchases under £100 on credit card', 
'[{"id":"cardProvider","label":"Credit Card Provider","type":"text","required":true},{"id":"purchaseDate","label":"Purchase Date","type":"date","required":true},{"id":"amount","label":"Purchase Amount","type":"text","required":true},{"id":"merchantName","label":"Merchant/Retailer Name","type":"text","required":true},{"id":"itemDescription","label":"Item/Service Description","type":"text","required":true},{"id":"issueDescription","label":"Problem Description","type":"textarea","required":true},{"id":"merchantStatus","label":"Merchant Status","type":"select","options":["Out of business","Not responding","Refusing refund"],"required":true}]',
'You are a professional letter writer helping a customer make a Section 75A claim for purchases under £100. Write a formal letter citing Section 75A of the Consumer Credit Act 1974, explaining that while the card provider is not jointly liable, they should assist in recovering funds through chargeback or other means. Explain the issue, why the merchant cannot/will not resolve it, and request the card provider''s assistance in recovering the money.'
FROM categories WHERE slug = 'chargeback-disputes';

INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Fraudulent Transaction Dispute', 'fraudulent-transaction', 'Report and dispute unauthorized card transactions', 
'[{"id":"cardProvider","label":"Bank/Card Provider","type":"text","required":true},{"id":"transactionDate","label":"Transaction Date","type":"date","required":true},{"id":"amount","label":"Transaction Amount","type":"text","required":true},{"id":"merchantName","label":"Merchant Name","type":"text","required":true},{"id":"discoveryDate","label":"When Did You Discover It","type":"date","required":true},{"id":"cardStatus","label":"Was Your Card in Your Possession?","type":"select","options":["Yes, card was with me","No, card was lost/stolen","Card details compromised online"],"required":true},{"id":"reportedToPolice","label":"Have You Reported to Police?","type":"select","options":["Yes","No","Not yet"],"required":true}]',
'You are a professional letter writer helping a customer dispute a fraudulent transaction. Write a formal letter stating clearly that the transaction was not authorized, referencing Payment Services Regulations 2017 which protects consumers from unauthorized transactions, explaining when and how you discovered it, confirming the card status, and requesting immediate refund of the fraudulent amount. Request temporary freeze on the account if needed.'
FROM categories WHERE slug = 'chargeback-disputes';

INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Merchant Not Responding', 'merchant-not-responding', 'Escalate to your bank when merchant ignores complaints', 
'[{"id":"bankName","label":"Bank/Card Provider Name","type":"text","required":true},{"id":"transactionDate","label":"Transaction Date","type":"date","required":true},{"id":"amount","label":"Transaction Amount","type":"text","required":true},{"id":"merchantName","label":"Merchant Name","type":"text","required":true},{"id":"issue","label":"Issue with Purchase","type":"textarea","required":true},{"id":"contactAttempts","label":"Contact Attempts Made","type":"textarea","required":true},{"id":"lastContactDate","label":"Last Contact Attempt Date","type":"date","required":true}]',
'You are a professional letter writer helping a customer escalate a dispute when the merchant is not responding. Write a formal letter to the bank/card provider explaining the purchase issue, documenting all contact attempts with the merchant and their lack of response, and requesting the bank to intervene via chargeback or Section 75 claim (if applicable). Emphasize the merchant''s failure to respond despite multiple attempts.'
FROM categories WHERE slug = 'chargeback-disputes';

INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Product Not Received (bank dispute format)', 'product-not-received-bank', 'Bank-specific format for non-delivery disputes', 
'[{"id":"bankName","label":"Bank Name","type":"text","required":true},{"id":"cardNumber","label":"Last 4 Digits of Card","type":"text","required":true},{"id":"transactionDate","label":"Transaction Date","type":"date","required":true},{"id":"amount","label":"Transaction Amount","type":"text","required":true},{"id":"merchantName","label":"Merchant Name","type":"text","required":true},{"id":"orderNumber","label":"Order Number","type":"text","required":true},{"id":"expectedDelivery","label":"Expected Delivery Date","type":"date","required":true},{"id":"trackingInfo","label":"Tracking Information","type":"text","required":false},{"id":"merchantContact","label":"Merchant Contact Attempts","type":"textarea","required":true}]',
'You are a professional letter writer helping a customer dispute a payment for a product not received, formatted for bank processing. Write a formal letter to the bank clearly stating: the transaction was for a product that was never delivered, delivery was expected by a certain date, tracking shows non-delivery (if applicable), merchant has not resolved despite contact, and you are formally requesting a chargeback or reversal. Use clear, factual language suitable for bank processing.'
FROM categories WHERE slug = 'chargeback-disputes';
