-- Insurance Templates  
INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Claim Payout Dispute', 'claim-payout-dispute', 'Challenge an unfair insurance claim payout amount', 
'[{"id":"insuranceCompany","label":"Insurance Company Name","type":"text","required":true},{"id":"policyNumber","label":"Policy Number","type":"text","required":true},{"id":"claimNumber","label":"Claim Number","type":"text","required":true},{"id":"incidentDate","label":"Incident Date","type":"date","required":true},{"id":"claimType","label":"Type of Claim","type":"select","options":["Car insurance","Home insurance","Travel insurance","Health insurance","Life insurance","Other"],"required":true},{"id":"offeredAmount","label":"Amount Offered","type":"text","required":true},{"id":"expectedAmount","label":"Amount You Believe is Fair","type":"text","required":true},{"id":"reasonForDispute","label":"Why is the Payout Unfair?","type":"textarea","required":true},{"id":"evidence","label":"Evidence to Support Your Claim","type":"textarea","required":true}]',
'You are a professional letter writer helping a customer dispute an unfair insurance claim payout. Write a formal letter citing Insurance Conduct of Business rules (ICOBS), explaining why the offered payout is insufficient, providing evidence of actual costs/value, and requesting a fair reassessment. Reference independent valuations, repair quotes, or replacement costs as appropriate.'
FROM categories WHERE slug = 'insurance';

INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Rejecting an Unfair Rejection', 'rejecting-unfair-rejection', 'Challenge when your insurance claim is wrongly denied', 
'[{"id":"insuranceCompany","label":"Insurance Company Name","type":"text","required":true},{"id":"policyNumber","label":"Policy Number","type":"text","required":true},{"id":"claimNumber","label":"Claim Number","type":"text","required":true},{"id":"incidentDate","label":"Incident Date","type":"date","required":true},{"id":"claimDescription","label":"Claim Description","type":"textarea","required":true},{"id":"rejectionReason","label":"Reason Given for Rejection","type":"textarea","required":true},{"id":"whyUnfair","label":"Why You Believe the Rejection is Unfair","type":"textarea","required":true},{"id":"policyEvidence","label":"Policy Evidence Supporting Your Claim","type":"textarea","required":true}]',
'You are a professional letter writer helping a customer challenge an unfair insurance claim rejection. Write a formal letter citing the specific policy terms that cover the claim, explaining why the rejection reason is invalid or misapplied, referencing ICOBS and FCA regulations requiring fair treatment of customers, and requesting immediate reconsideration. Warn of escalation to Financial Ombudsman Service if not resolved.'
FROM categories WHERE slug = 'insurance';

INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Delayed Claim Complaint', 'delayed-claim-complaint', 'Complain about excessive delays in claim processing', 
'[{"id":"insuranceCompany","label":"Insurance Company Name","type":"text","required":true},{"id":"policyNumber","label":"Policy Number","type":"text","required":true},{"id":"claimNumber","label":"Claim Number","type":"text","required":true},{"id":"claimDate","label":"When Was Claim Submitted","type":"date","required":true},{"id":"claimType","label":"Type of Claim","type":"text","required":true},{"id":"daysPassed","label":"Days Since Claim Submitted","type":"text","required":true},{"id":"contactAttempts","label":"Contact Attempts Made","type":"textarea","required":true},{"id":"impact","label":"Impact of the Delay","type":"textarea","required":true}]',
'You are a professional letter writer helping a customer complain about excessive delays in insurance claim processing. Write a formal letter citing ICOBS rules requiring prompt claim handling, explaining the timeline of the delay, the impact on the customer, and requesting immediate action with a deadline. Reference the right to complain to Financial Ombudsman Service if delays continue unreasonably.'
FROM categories WHERE slug = 'insurance';

INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Providing Missing Documents', 'providing-missing-documents', 'Submit requested documentation for your claim', 
'[{"id":"insuranceCompany","label":"Insurance Company Name","type":"text","required":true},{"id":"policyNumber","label":"Policy Number","type":"text","required":true},{"id":"claimNumber","label":"Claim Number","type":"text","required":true},{"id":"requestDate","label":"When Were Documents Requested","type":"date","required":true},{"id":"documentsRequested","label":"Documents That Were Requested","type":"textarea","required":true},{"id":"documentsProviding","label":"Documents You Are Now Providing","type":"textarea","required":true},{"id":"reasonForDelay","label":"Reason for Delay (if any)","type":"textarea","required":false}]',
'You are a professional letter writer helping a customer provide missing documents to support an insurance claim. Write a formal cover letter listing all documents enclosed, referencing the claim number and previous request, confirming these documents should complete the claim requirements, and requesting prompt processing of the claim now that all information has been provided.'
FROM categories WHERE slug = 'insurance';

INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Incorrect Excess Charged', 'incorrect-excess-charged', 'Challenge when you''re charged the wrong excess amount', 
'[{"id":"insuranceCompany","label":"Insurance Company Name","type":"text","required":true},{"id":"policyNumber","label":"Policy Number","type":"text","required":true},{"id":"claimNumber","label":"Claim Number","type":"text","required":true},{"id":"excessCharged","label":"Excess Amount Charged","type":"text","required":true},{"id":"correctExcess","label":"Correct Excess Amount","type":"text","required":true},{"id":"policyEvidence","label":"Where in Policy is Correct Excess Stated","type":"textarea","required":true},{"id":"paymentDate","label":"When Was Excess Paid","type":"date","required":true}]',
'You are a professional letter writer helping a customer dispute an incorrect excess charge. Write a formal letter citing the exact policy terms showing the correct excess amount, explaining the overcharge clearly with calculations, and requesting an immediate refund of the difference plus an explanation of how the error occurred. Reference ICOBS requirement for transparency and accuracy in policy administration.'
FROM categories WHERE slug = 'insurance';
