-- Car Dealer Disputes Templates
INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Reject Car Under Consumer Rights Act 2015', 'reject-car-cra', 'Exercise your right to reject a faulty car within 30 days', 
'[{"id":"dealerName","label":"Dealer Name","type":"text","required":true},{"id":"dealerAddress","label":"Dealer Address","type":"textarea","required":true},{"id":"purchaseDate","label":"Purchase Date","type":"date","required":true},{"id":"vehicleMake","label":"Vehicle Make/Model","type":"text","required":true},{"id":"registrationNumber","label":"Registration Number","type":"text","required":true},{"id":"purchasePrice","label":"Purchase Price","type":"text","required":true},{"id":"faultDescription","label":"Fault Description","type":"textarea","required":true},{"id":"daysSincePurchase","label":"Days Since Purchase","type":"text","required":true}]',
'You are a professional letter writer helping a customer reject a faulty car under Consumer Rights Act 2015. Write a formal letter citing the short-term right to reject (30 days for minor problems, immediate for serious faults), clearly describing the fault and why it makes the car not of satisfactory quality or fit for purpose, stating you are formally rejecting the vehicle, and requesting a full refund including any finance charges, fees, and collection of the vehicle at their expense.'
FROM categories WHERE slug = 'car-dealer';

INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Request Repair Under CRA', 'request-repair-cra', 'Request the dealer repair a fault under warranty', 
'[{"id":"dealerName","label":"Dealer Name","type":"text","required":true},{"id":"purchaseDate","label":"Purchase Date","type":"date","required":true},{"id":"vehicleMake","label":"Vehicle Make/Model","type":"text","required":true},{"id":"registrationNumber","label":"Registration Number","type":"text","required":true},{"id":"mileageAtPurchase","label":"Mileage at Purchase","type":"text","required":true},{"id":"currentMileage","label":"Current Mileage","type":"text","required":true},{"id":"faultDescription","label":"Fault Description","type":"textarea","required":true},{"id":"whenFaultOccurred","label":"When Did Fault Occur","type":"date","required":true}]',
'You are a professional letter writer helping a customer request a repair under Consumer Rights Act 2015. Write a formal letter explaining the fault, citing CRA rights (goods must be of satisfactory quality and last a reasonable time), requesting a free repair within a reasonable time, and warning that if repair fails or is unreasonable, you will request replacement or partial refund. Set a reasonable deadline (e.g., 14 days for initial response).'
FROM categories WHERE slug = 'car-dealer';

INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Car Mis-Sold (incorrect spec/damaged)', 'car-mis-sold', 'Challenge misrepresentation or undisclosed damage', 
'[{"id":"dealerName","label":"Dealer Name","type":"text","required":true},{"id":"purchaseDate","label":"Purchase Date","type":"date","required":true},{"id":"vehicleMake","label":"Vehicle Make/Model","type":"text","required":true},{"id":"registrationNumber","label":"Registration Number","type":"text","required":true},{"id":"purchasePrice","label":"Purchase Price","type":"text","required":true},{"id":"whatWasPromised","label":"What Was Advertised/Promised","type":"textarea","required":true},{"id":"actualCondition","label":"Actual Condition/Specification","type":"textarea","required":true},{"id":"evidence","label":"Evidence of Misrepresentation","type":"textarea","required":true}]',
'You are a professional letter writer helping a customer challenge a mis-sold vehicle. Write a formal letter citing Consumer Protection from Unfair Trading Regulations 2008 and Consumer Rights Act 2015, clearly comparing what was advertised/promised vs what was actually delivered, explaining this constitutes misrepresentation, and requesting either a full refund with rejection of the vehicle, or appropriate compensation reflecting the difference in value. Reference evidence such as advertisements, inspection reports, or vehicle history checks.'
FROM categories WHERE slug = 'car-dealer';

INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Warranty Repair Dispute', 'warranty-repair-dispute', 'Challenge unfair warranty claim rejections', 
'[{"id":"dealerName","label":"Dealer/Warranty Company Name","type":"text","required":true},{"id":"warrantyType","label":"Warranty Type","type":"select","options":["Manufacturer warranty","Extended warranty","Dealer warranty","Third-party warranty"],"required":true},{"id":"vehicleMake","label":"Vehicle Make/Model","type":"text","required":true},{"id":"registrationNumber","label":"Registration Number","type":"text","required":true},{"id":"faultDescription","label":"Fault Description","type":"textarea","required":true},{"id":"repairCost","label":"Estimated Repair Cost","type":"text","required":true},{"id":"rejectionReason","label":"Reason Given for Warranty Rejection","type":"textarea","required":true},{"id":"whyUnfair","label":"Why the Rejection is Unfair","type":"textarea","required":true}]',
'You are a professional letter writer helping a customer dispute a warranty claim rejection. Write a formal letter referencing the warranty terms, explaining why the fault should be covered, challenging the rejection reason with evidence or warranty clause citations, and requesting the repair be authorized. If the warranty rejection is clearly unfair, cite Consumer Rights Act 2015 which provides rights beyond warranty for inherent faults. Request escalation to a senior manager or independent review.'
FROM categories WHERE slug = 'car-dealer';

INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Deposit Refund Request', 'deposit-refund-request', 'Request return of deposit for cancelled vehicle purchase', 
'[{"id":"dealerName","label":"Dealer Name","type":"text","required":true},{"id":"depositDate","label":"Deposit Payment Date","type":"date","required":true},{"id":"depositAmount","label":"Deposit Amount","type":"text","required":true},{"id":"vehicleDetails","label":"Vehicle Details","type":"text","required":true},{"id":"cancellationReason","label":"Reason for Cancellation","type":"textarea","required":true},{"id":"dealerFault","label":"Was Cancellation Due to Dealer Fault?","type":"select","options":["Yes - dealer breached contract","Yes - vehicle not as described","No - my circumstances changed","No - changed my mind"],"required":true},{"id":"cancellationDate","label":"When Did You Cancel","type":"date","required":true}]',
'You are a professional letter writer helping a customer request a deposit refund. Write a formal letter explaining the reason for cancellation, citing relevant law (if dealer at fault: Consumer Rights Act 2015; if cooling off period applies: Consumer Contracts Regulations 2013), and requesting full refund of the deposit. If dealer is at fault, argue strongly for full refund. If customer cancelled without cause, acknowledge any reasonable admin fees but challenge excessive retention.'
FROM categories WHERE slug = 'car-dealer';

INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Finance Agreement Cancellation Request', 'finance-cancellation', 'Cancel car finance agreement and return vehicle', 
'[{"id":"financeCompany","label":"Finance Company Name","type":"text","required":true},{"id":"agreementNumber","label":"Agreement Number","type":"text","required":true},{"id":"agreementDate","label":"Agreement Date","type":"date","required":true},{"id":"vehicleDetails","label":"Vehicle Details","type":"text","required":true},{"id":"monthlyPayment","label":"Monthly Payment Amount","type":"text","required":true},{"id":"totalPaid","label":"Total Amount Paid So Far","type":"text","required":true},{"id":"cancellationReason","label":"Reason for Cancellation","type":"textarea","required":true},{"id":"vehicleIssues","label":"Any Issues with the Vehicle?","type":"textarea","required":false}]',
'You are a professional letter writer helping a customer cancel a car finance agreement. Write a formal letter citing relevant sections: Consumer Credit Act 1974 (right to withdraw within 14 days or terminate HP/PCP early), explaining the reason for cancellation, calculating any settlement figure or refund due, and requesting confirmation of cancellation, final balance, and vehicle collection arrangements. If there are vehicle faults, argue these may constitute misrepresentation and strengthen the cancellation case.'
FROM categories WHERE slug = 'car-dealer';

INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Mileage Discrepancy Complaint', 'mileage-discrepancy', 'Challenge incorrect or clocked mileage', 
'[{"id":"dealerName","label":"Dealer Name","type":"text","required":true},{"id":"purchaseDate","label":"Purchase Date","type":"date","required":true},{"id":"vehicleDetails","label":"Vehicle Make/Model/Registration","type":"text","required":true},{"id":"purchasePrice","label":"Purchase Price","type":"text","required":true},{"id":"advertisedMileage","label":"Advertised/Stated Mileage","type":"text","required":true},{"id":"actualMileage","label":"Actual/Verified Mileage","type":"text","required":true},{"id":"evidenceSource","label":"How Was Discrepancy Discovered","type":"textarea","required":true},{"id":"valueImpact","label":"Impact on Vehicle Value","type":"text","required":true}]',
'You are a professional letter writer helping a customer challenge a mileage discrepancy. Write a formal letter citing Fraud Act 2006 (clocking is fraud) and Consumer Protection from Unfair Trading Regulations 2008, explaining the mileage discrepancy with evidence (MOT history, service records, HPI check), the impact on value, and requesting either full refund with vehicle return, or substantial compensation reflecting the true value vs price paid. Emphasize this is a serious offense and you will report to Trading Standards if not resolved.'
FROM categories WHERE slug = 'car-dealer';
