-- Landlord / Tenant Templates
INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Deposit Return Request', 'deposit-return-request', 'Request return of your tenancy deposit', 
'[{"id":"landlordName","label":"Landlord Name","type":"text","required":true},{"id":"propertyAddress","label":"Property Address","type":"textarea","required":true},{"id":"tenancyStartDate","label":"Tenancy Start Date","type":"date","required":true},{"id":"tenancyEndDate","label":"Tenancy End Date","type":"date","required":true},{"id":"depositAmount","label":"Deposit Amount","type":"text","required":true},{"id":"depositScheme","label":"Deposit Protection Scheme","type":"text","required":true},{"id":"deductionsClaimed","label":"Deductions Claimed by Landlord","type":"textarea","required":false},{"id":"propertyCondition","label":"Property Condition on Exit","type":"textarea","required":true}]',
'You are a professional letter writer helping a tenant request their deposit return. Write a formal letter citing Housing Act 2004 and Tenancy Deposit Scheme rules, referencing the deposit protection details, explaining the property was left in good condition (fair wear and tear expected), challenging any unfair deduction claims, and requesting full return of the deposit within the statutory timeframe. Warn of adjudication if agreement cannot be reached.'
FROM categories WHERE slug = 'landlord-tenant';

INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Notice to End Tenancy', 'notice-end-tenancy', 'Serve formal notice to end your tenancy', 
'[{"id":"landlordName","label":"Landlord Name","type":"text","required":true},{"id":"propertyAddress","label":"Property Address","type":"textarea","required":true},{"id":"tenancyType","label":"Tenancy Type","type":"select","options":["Assured Shorthold Tenancy","Periodic Tenancy","Fixed Term (ending soon)"],"required":true},{"id":"noticeDate","label":"Date of This Notice","type":"date","required":true},{"id":"intendedLeaveDate","label":"Intended Leave Date","type":"date","required":true},{"id":"noticePeriod","label":"Notice Period Required","type":"text","required":true},{"id":"forwardingAddress","label":"Forwarding Address for Deposit Return","type":"textarea","required":true}]',
'You are a professional letter writer helping a tenant serve notice to end their tenancy. Write a formal letter stating clearly the intention to end the tenancy, the notice date, the intended leave date, confirming the required notice period is being met, and requesting acknowledgement, return of deposit details, and final meter reading arrangements. Keep it professional and factual.'
FROM categories WHERE slug = 'landlord-tenant';

INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Repairs Request', 'repairs-request', 'Request landlord to carry out necessary repairs', 
'[{"id":"landlordName","label":"Landlord Name","type":"text","required":true},{"id":"propertyAddress","label":"Property Address","type":"textarea","required":true},{"id":"repairsNeeded","label":"Repairs Needed","type":"textarea","required":true},{"id":"whenReported","label":"When Was Issue First Reported","type":"date","required":true},{"id":"previousRequests","label":"Previous Repair Requests","type":"textarea","required":false},{"id":"urgency","label":"Urgency Level","type":"select","options":["Emergency (health/safety risk)","Urgent","Non-urgent"],"required":true},{"id":"impact","label":"Impact on Your Use of Property","type":"textarea","required":true}]',
'You are a professional letter writer helping a tenant request repairs from their landlord. Write a formal letter citing Landlord and Tenant Act 1985 (landlord duty to maintain structure and installations), clearly listing repairs needed, explaining the impact on habitability/health, referencing previous requests if ignored, and setting a reasonable deadline (24 hours for emergency, 7 days for urgent, 28 days for non-urgent). Warn of Environmental Health involvement or rent withholding if repairs not completed.'
FROM categories WHERE slug = 'landlord-tenant';

INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Damp/Mould Complaint', 'damp-mould-complaint', 'Report serious damp or mould issues', 
'[{"id":"landlordName","label":"Landlord Name","type":"text","required":true},{"id":"propertyAddress","label":"Property Address","type":"textarea","required":true},{"id":"issueDescription","label":"Description of Damp/Mould","type":"textarea","required":true},{"id":"affectedAreas","label":"Areas Affected","type":"textarea","required":true},{"id":"whenStarted","label":"When Did Issue Start","type":"date","required":true},{"id":"healthImpact","label":"Health Impact (if any)","type":"textarea","required":false},{"id":"previousReports","label":"Previous Reports to Landlord","type":"textarea","required":false},{"id":"photos","label":"Have You Taken Photos?","type":"select","options":["Yes","No"],"required":true}]',
'You are a professional letter writer helping a tenant complain about damp and mould. Write a formal, serious letter citing Housing Health and Safety Rating System (HHSRS) and landlord repair obligations, describing the damp/mould problem and affected areas, explaining any health impacts (especially respiratory issues), demanding immediate investigation and remedial works, and warning of Environmental Health notification if not resolved urgently. Emphasize this is a serious health hazard that makes the property unfit for habitation.'
FROM categories WHERE slug = 'landlord-tenant';

INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Harassment by Landlord', 'harassment-by-landlord', 'Complain about landlord harassment or illegal eviction attempts', 
'[{"id":"landlordName","label":"Landlord Name","type":"text","required":true},{"id":"propertyAddress","label":"Property Address","type":"textarea","required":true},{"id":"harassmentType","label":"Type of Harassment","type":"textarea","required":true},{"id":"incidents","label":"Detailed Description of Incidents","type":"textarea","required":true},{"id":"dates","label":"Dates of Incidents","type":"textarea","required":true},{"id":"witnesses","label":"Any Witnesses","type":"textarea","required":false},{"id":"evidence","label":"Evidence Available","type":"textarea","required":false}]',
'You are a professional letter writer helping a tenant address landlord harassment. Write a firm, formal letter citing Protection from Eviction Act 1977 and Protection from Harassment Act 1997, detailing specific incidents of harassment with dates and witnesses, demanding the harassment stops immediately, confirming your right to quiet enjoyment of the property, and warning that continued harassment will be reported to police and local authority. State clearly that only lawful eviction procedures (Section 21/Section 8 notice) are acceptable.'
FROM categories WHERE slug = 'landlord-tenant';

INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Eviction Response', 'eviction-response', 'Respond to eviction notice and assert your rights', 
'[{"id":"landlordName","label":"Landlord Name","type":"text","required":true},{"id":"propertyAddress","label":"Property Address","type":"textarea","required":true},{"id":"noticeType","label":"Type of Notice Received","type":"select","options":["Section 21 (no fault eviction)","Section 8 (grounds for eviction)","Invalid notice","Verbal threat only"],"required":true},{"id":"noticeDate","label":"Date Notice Received","type":"date","required":true},{"id":"noticeIssues","label":"Issues with the Notice","type":"textarea","required":false},{"id":"disputeGrounds","label":"Why You Are Disputing","type":"textarea","required":true},{"id":"depositProtected","label":"Was Deposit Protected Correctly?","type":"select","options":["Yes","No","Unknown"],"required":true}]',
'You are a professional letter writer helping a tenant respond to an eviction notice. Write a formal letter challenging any procedural errors in the notice (check: deposit protection, gas safety certificates, EPC, How to Rent guide, notice format and length), citing relevant law, explaining why the eviction is unjustified or the notice is invalid, and asserting the right to remain in the property unless a valid court order is obtained. If the notice is valid but harsh, request negotiation or additional time.'
FROM categories WHERE slug = 'landlord-tenant';

INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Tenancy Agreement Breach', 'tenancy-agreement-breach', 'Challenge landlord breaches of tenancy agreement', 
'[{"id":"landlordName","label":"Landlord Name","type":"text","required":true},{"id":"propertyAddress","label":"Property Address","type":"textarea","required":true},{"id":"breachDescription","label":"Breach of Agreement","type":"textarea","required":true},{"id":"contractClause","label":"Relevant Clause in Agreement","type":"textarea","required":true},{"id":"impact","label":"Impact on You","type":"textarea","required":true},{"id":"remedySought","label":"Remedy Sought","type":"textarea","required":true}]',
'You are a professional letter writer helping a tenant challenge a landlord breach of tenancy agreement. Write a formal letter citing the specific clause breached, explaining how the landlord has failed to meet their obligations, the impact on the tenant, and requesting immediate remedy (performance of obligation, compensation, or agreement to end tenancy without penalty). Reference contract law and statutory rights.'
FROM categories WHERE slug = 'landlord-tenant';

-- Workplace / HR Templates
INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Formal Grievance', 'formal-grievance', 'Raise a formal grievance at work', 
'[{"id":"recipientName","label":"Recipient Name (HR/Manager)","type":"text","required":true},{"id":"recipientTitle","label":"Recipient Job Title","type":"text","required":true},{"id":"companyName","label":"Company Name","type":"text","required":true},{"id":"yourPosition","label":"Your Position","type":"text","required":true},{"id":"grievanceSubject","label":"Subject of Grievance","type":"text","required":true},{"id":"grievanceDetails","label":"Detailed Description of Grievance","type":"textarea","required":true},{"id":"dates","label":"Relevant Dates","type":"textarea","required":true},{"id":"personsInvolved","label":"Persons Involved","type":"textarea","required":true},{"id":"previousAttempts","label":"Informal Resolution Attempts","type":"textarea","required":false},{"id":"remedySought","label":"Resolution Sought","type":"textarea","required":true}]',
'You are a professional letter writer helping an employee raise a formal workplace grievance. Write a formal letter following ACAS Code of Practice, clearly stating this is a formal grievance, describing the issue objectively with specific dates and facts, naming individuals involved, explaining the impact, referencing any informal attempts at resolution, and requesting a formal grievance meeting. State the desired outcome clearly. Maintain professionalism throughout.'
FROM categories WHERE slug = 'workplace';

INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Appeal Against Disciplinary Action', 'disciplinary-appeal', 'Appeal an unfair disciplinary decision', 
'[{"id":"recipientName","label":"Appeal Recipient Name","type":"text","required":true},{"id":"companyName","label":"Company Name","type":"text","required":true},{"id":"yourPosition","label":"Your Position","type":"text","required":true},{"id":"disciplinaryDate","label":"Disciplinary Meeting Date","type":"date","required":true},{"id":"disciplinaryOutcome","label":"Disciplinary Outcome","type":"textarea","required":true},{"id":"appealGrounds","label":"Grounds for Appeal","type":"textarea","required":true},{"id":"proceduralFlaws","label":"Any Procedural Flaws","type":"textarea","required":false},{"id":"newEvidence","label":"New Evidence (if any)","type":"textarea","required":false}]',
'You are a professional letter writer helping an employee appeal a disciplinary decision. Write a formal appeal letter citing ACAS Code of Practice, clearly stating you are appealing the disciplinary outcome, explaining grounds for appeal (procedural errors, unfair outcome, new evidence, mitigating circumstances not considered), requesting an appeal hearing with a different manager, and reserving the right to bring a companion. Be firm but professional, focus on facts and fairness.'
FROM categories WHERE slug = 'workplace';

INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Response to Suspension', 'suspension-response', 'Respond formally to workplace suspension', 
'[{"id":"recipientName","label":"Recipient Name","type":"text","required":true},{"id":"companyName","label":"Company Name","type":"text","required":true},{"id":"yourPosition","label":"Your Position","type":"text","required":true},{"id":"suspensionDate","label":"Suspension Date","type":"date","required":true},{"id":"suspensionReason","label":"Reason Given for Suspension","type":"textarea","required":true},{"id":"yourResponse","label":"Your Response to Allegations","type":"textarea","required":true},{"id":"suspensionPaid","label":"Is Suspension Paid?","type":"select","options":["Yes","No","Not stated"],"required":true}]',
'You are a professional letter writer helping an employee respond to suspension. Write a formal letter acknowledging the suspension, responding to the allegations (denying if false, or explaining if true), requesting full details of the allegations and investigation process, confirming availability for investigation meetings, and requesting the suspension is kept as short as possible. Ensure suspension is on full pay as is standard. Maintain professionalism and cooperate with the process while defending your position.'
FROM categories WHERE slug = 'workplace';

INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Flexible Working Request', 'flexible-working-request', 'Request flexible working arrangements', 
'[{"id":"recipientName","label":"Manager/HR Name","type":"text","required":true},{"id":"companyName","label":"Company Name","type":"text","required":true},{"id":"yourPosition","label":"Your Position","type":"text","required":true},{"id":"lengthOfService","label":"Length of Service","type":"text","required":true},{"id":"requestType","label":"Type of Flexible Working","type":"select","options":["Work from home","Reduced hours","Flexible hours","Compressed hours","Job share","Other"],"required":true},{"id":"proposedArrangement","label":"Proposed Arrangement Details","type":"textarea","required":true},{"id":"startDate","label":"Proposed Start Date","type":"date","required":true},{"id":"reasonForRequest","label":"Reason for Request","type":"textarea","required":true},{"id":"businessImpact","label":"How You Will Maintain Performance","type":"textarea","required":true}]',
'You are a professional letter writer helping an employee request flexible working. Write a formal letter citing Employment Rights Act 1996 (right to request after 26 weeks service), clearly stating this is a statutory flexible working request, describing the proposed arrangement in detail, explaining the business case (how work will be covered, minimal impact), and requesting a meeting to discuss. Be professional and solution-focused, showing you have considered business needs.'
FROM categories WHERE slug = 'workplace';

INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Harassment/Bullying Complaint', 'harassment-bullying-complaint', 'Report workplace harassment or bullying', 
'[{"id":"recipientName","label":"HR/Manager Name","type":"text","required":true},{"id":"companyName","label":"Company Name","type":"text","required":true},{"id":"yourPosition","label":"Your Position","type":"text","required":true},{"id":"perpetrator","label":"Person(s) Involved","type":"text","required":true},{"id":"incidentDetails","label":"Detailed Description of Incidents","type":"textarea","required":true},{"id":"dates","label":"Dates of Incidents","type":"textarea","required":true},{"id":"witnesses","label":"Witnesses (if any)","type":"textarea","required":false},{"id":"impact","label":"Impact on Your Health/Work","type":"textarea","required":true},{"id":"previousReports","label":"Previous Reports Made","type":"textarea","required":false}]',
'You are a professional letter writer helping an employee report workplace harassment or bullying. Write a serious, formal letter citing Equality Act 2010 (if harassment is related to protected characteristic) and employer duty of care, describing specific incidents with dates objectively, explaining the severe impact on health and work, requesting immediate investigation and action to prevent further incidents, and stating you may need to take sick leave or involve external agencies if not resolved. Request a formal meeting and written response.'
FROM categories WHERE slug = 'workplace';

-- Traffic / Speeding Templates
INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Speeding Mitigation Letter', 'speeding-mitigation', 'Provide mitigation for a speeding offense', 
'[{"id":"recipientCourt","label":"Court Name","type":"text","required":true},{"id":"noticeNumber","label":"Notice Number","type":"text","required":true},{"id":"offenseDate","label":"Offense Date","type":"date","required":true},{"id":"location","label":"Location","type":"text","required":true},{"id":"speedLimit","label":"Speed Limit","type":"text","required":true},{"id":"recordedSpeed","label":"Recorded Speed","type":"text","required":true},{"id":"mitigatingCircumstances","label":"Mitigating Circumstances","type":"textarea","required":true},{"id":"drivingRecord","label":"Your Driving Record","type":"textarea","required":true},{"id":"personalCircumstances","label":"Personal Circumstances","type":"textarea","required":true}]',
'You are a professional letter writer helping a driver provide mitigation for a speeding offense. Write a formal letter to the court accepting responsibility (if appropriate), explaining mitigating circumstances (emergency, road works, brief lapse, exceptional circumstances), emphasizing a previously clean driving record, explaining the impact of a ban on employment/family, and requesting the court consider the minimum penalty or speed awareness course. Be respectful and show genuine remorse.'
FROM categories WHERE slug = 'traffic';

INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Incorrect NIP (Notice of Intended Prosecution)', 'incorrect-nip', 'Challenge a defective NIP', 
'[{"id":"policeForceName","label":"Police Force Name","type":"text","required":true},{"id":"nipReference","label":"NIP Reference Number","type":"text","required":true},{"id":"offenseDate","label":"Alleged Offense Date","type":"date","required":true},{"id":"nipReceiveDate","label":"Date You Received NIP","type":"date","required":true},{"id":"defectReason","label":"Why NIP is Defective","type":"select","options":["Received more than 14 days after offense","Incorrect vehicle details","Incorrect driver details","Unclear offense details","Not registered keeper"],"required":true},{"id":"explanation","label":"Detailed Explanation","type":"textarea","required":true}]',
'You are a professional letter writer helping a driver challenge a defective NIP. Write a formal letter citing Road Traffic Offenders Act 1988 Section 1 (NIP must be served within 14 days), clearly explaining the defect (late service, incorrect details, etc.), providing evidence where available, and requesting the prosecution be discontinued due to the defective NIP. Be factual and cite the specific legal requirement that was not met.'
FROM categories WHERE slug = 'traffic';

INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Appeal for Wrong PCN', 'appeal-wrong-pcn', 'Appeal an incorrectly issued parking ticket', 
'[{"id":"councilName","label":"Council/Issuing Authority Name","type":"text","required":true},{"id":"pcnNumber","label":"PCN Number","type":"text","required":true},{"id":"issueDate","label":"Issue Date","type":"date","required":true},{"id":"location","label":"Location","type":"text","required":true},{"id":"vehicleReg","label":"Vehicle Registration","type":"text","required":true},{"id":"reasonWrong","label":"Why PCN is Wrong","type":"textarea","required":true},{"id":"evidence","label":"Evidence to Support Appeal","type":"textarea","required":true}]',
'You are a professional letter writer helping a driver appeal an incorrect PCN. Write a formal appeal letter citing Traffic Management Act 2004 and local authority parking rules, clearly explaining why the PCN is incorrect (valid ticket displayed, Blue Badge holder, incorrect contravention code, loading/unloading, emergency, signage unclear), providing evidence (photos, receipts, timestamps), and requesting cancellation. Be factual and provide clear evidence.'
FROM categories WHERE slug = 'traffic';

INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Appeal for Unclear Signage', 'appeal-unclear-signage', 'Challenge PCN due to poor or missing signs', 
'[{"id":"councilName","label":"Council Name","type":"text","required":true},{"id":"pcnNumber","label":"PCN Number","type":"text","required":true},{"id":"issueDate","label":"Issue Date","type":"date","required":true},{"id":"location","label":"Location","type":"text","required":true},{"id":"signageIssue","label":"Signage Issue","type":"textarea","required":true},{"id":"photos","label":"Have You Taken Photos?","type":"select","options":["Yes","No"],"required":true},{"id":"reasonableDriver","label":"Why Signs Were Unclear to Reasonable Driver","type":"textarea","required":true}]',
'You are a professional letter writer helping a driver appeal a PCN due to unclear signage. Write a formal appeal citing Traffic Signs Regulations and General Directions 2016 (signs must be clearly visible and compliant), describing specifically why the signage was inadequate (missing, obscured, contradictory, non-compliant), arguing a reasonable driver could not have known about the restriction, requesting site visit or adjudicator review with photos, and requesting cancellation. Strong emphasis on the legal requirement for clear, compliant signage.'
FROM categories WHERE slug = 'traffic';

INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Appeal for Faulty Camera Evidence', 'appeal-faulty-camera', 'Challenge speed camera evidence', 
'[{"id":"policeForceName","label":"Police Force Name","type":"text","required":true},{"id":"nipReference","label":"NIP Reference","type":"text","required":true},{"id":"offenseDate","label":"Alleged Offense Date","type":"date","required":true},{"id":"location","label":"Location","type":"text","required":true},{"id":"cameraType","label":"Camera Type (if known)","type":"text","required":false},{"id":"challengeReason","label":"Reason to Challenge Camera Evidence","type":"textarea","required":true},{"id":"evidenceRequested","label":"Evidence You Are Requesting","type":"textarea","required":true}]',
'You are a professional letter writer helping a driver challenge speed camera evidence. Write a formal letter citing the Association of Chief Police Officers guidelines for speed cameras and Road Traffic Offenders Act 1988, challenging the reliability of the camera (calibration, maintenance records, photographic evidence quality, multiple vehicle ambiguity), requesting full disclosure of evidence including camera certificate, calibration records, site survey, and photographic evidence. Request withdrawal if evidence cannot be provided or is defective.'
FROM categories WHERE slug = 'traffic';

-- Travel & Airline Templates
INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Flight Delay Compensation (EU261)', 'flight-delay-eu261', 'Claim compensation for delayed EU flights', 
'[{"id":"airlineName","label":"Airline Name","type":"text","required":true},{"id":"flightNumber","label":"Flight Number","type":"text","required":true},{"id":"flightDate","label":"Flight Date","type":"date","required":true},{"id":"departureAirport","label":"Departure Airport","type":"text","required":true},{"id":"arrivalAirport","label":"Arrival Airport","type":"text","required":true},{"id":"scheduledDeparture","label":"Scheduled Departure Time","type":"text","required":true},{"id":"actualArrival","label":"Actual Arrival Time","type":"text","required":true},{"id":"delayLength","label":"Length of Delay (hours)","type":"text","required":true},{"id":"bookingReference","label":"Booking Reference","type":"text","required":true},{"id":"passengersAffected","label":"Number of Passengers Claiming","type":"text","required":true}]',
'You are a professional letter writer helping a passenger claim EU261 flight delay compensation. Write a formal letter citing Regulation (EC) No 261/2004, stating the flight details, the length of delay, and calculating the compensation due (€250/€400/€600 depending on distance and delay), requesting payment within 14 days. Reference the airline duty to pay unless extraordinary circumstances proven (burden of proof on airline). Request written explanation if compensation is refused.'
FROM categories WHERE slug = 'travel';

INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Cancelled Flight Refund', 'cancelled-flight-refund', 'Request refund for cancelled flight', 
'[{"id":"airlineName","label":"Airline Name","type":"text","required":true},{"id":"flightNumber","label":"Flight Number","type":"text","required":true},{"id":"flightDate","label":"Scheduled Flight Date","type":"date","required":true},{"id":"bookingReference","label":"Booking Reference","type":"text","required":true},{"id":"bookingAmount","label":"Amount Paid","type":"text","required":true},{"id":"cancellationNotice","label":"When Were You Notified of Cancellation","type":"date","required":true},{"id":"alternativeFlight","label":"Was Alternative Flight Offered?","type":"select","options":["Yes, but unsuitable","Yes, but declined","No"],"required":true},{"id":"compensation","label":"Are You Also Claiming EU261 Compensation?","type":"select","options":["Yes","No"],"required":true}]',
'You are a professional letter writer helping a passenger request a refund for a cancelled flight. Write a formal letter citing EU261 (right to refund within 7 days for cancelled flights) or package holiday regulations if applicable, requesting full refund of ticket price, and if cancelled less than 14 days before departure without extraordinary circumstances, also requesting compensation (€250-€600 depending on distance and notice). Request refund to original payment method within 7 days.'
FROM categories WHERE slug = 'travel';

INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Lost Luggage Claim', 'lost-luggage-claim', 'Claim compensation for lost luggage', 
'[{"id":"airlineName","label":"Airline Name","type":"text","required":true},{"id":"flightNumber","label":"Flight Number","type":"text","required":true},{"id":"flightDate","label":"Flight Date","type":"date","required":true},{"id":"bookingReference","label":"Booking Reference","type":"text","required":true},{"id":"pirReference","label":"PIR Reference Number","type":"text","required":true},{"id":"bagsLost","label":"Number of Bags Lost","type":"text","required":true},{"id":"contentsValue","label":"Estimated Contents Value","type":"text","required":true},{"id":"itemsList","label":"List of Contents","type":"textarea","required":true},{"id":"receipts","label":"Do You Have Receipts for Items?","type":"select","options":["Yes, for some items","Yes, for most items","No"],"required":true}]',
'You are a professional letter writer helping a passenger claim for lost luggage. Write a formal letter citing Montreal Convention (airline liability up to approx £1,100 per passenger), referencing the PIR number, itemizing lost contents with values and receipts where available, requesting either luggage recovery or financial compensation for the loss. If luggage delayed initially, include expense claims for emergency purchases. Request settlement within reasonable timeframe.'
FROM categories WHERE slug = 'travel';

INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Seat Downgrade Refund', 'seat-downgrade-refund', 'Claim refund for involuntary seat downgrade', 
'[{"id":"airlineName","label":"Airline Name","type":"text","required":true},{"id":"flightNumber","label":"Flight Number","type":"text","required":true},{"id":"flightDate","label":"Flight Date","type":"date","required":true},{"id":"bookingReference","label":"Booking Reference","type":"text","required":true},{"id":"bookedClass","label":"Class Booked and Paid For","type":"text","required":true},{"id":"actualClass","label":"Class Actually Flown","type":"text","required":true},{"id":"ticketPrice","label":"Ticket Price Paid","type":"text","required":true},{"id":"noticeGiven","label":"When Were You Notified of Downgrade","type":"text","required":true}]',
'You are a professional letter writer helping a passenger claim a refund for involuntary seat downgrade. Write a formal letter citing EU261 Regulation Article 10 which requires refund of 30-75% of ticket price depending on flight distance when passenger is downgraded, explaining you were downgraded from [booked class] to [actual class], calculating the refund due, and requesting payment within 14 days. Express disappointment at the service failure.'
FROM categories WHERE slug = 'travel';

INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Hotel Booking Refund', 'hotel-booking-refund', 'Request refund for hotel booking issues', 
'[{"id":"hotelName","label":"Hotel Name","type":"text","required":true},{"id":"bookingReference","label":"Booking Reference","type":"text","required":true},{"id":"bookingDate","label":"Booking Date","type":"date","required":true},{"id":"stayDates","label":"Stay Dates","type":"text","required":true},{"id":"amountPaid","label":"Amount Paid","type":"text","required":true},{"id":"issue","label":"Issue with Booking","type":"select","options":["Hotel cancelled booking","Room not as described","Hygiene/cleanliness issues","Facilities not available","Overbooked","Other"],"required":true},{"id":"issueDetails","label":"Detailed Description of Issue","type":"textarea","required":true},{"id":"alternativeArrangement","label":"Did You Need Alternative Accommodation?","type":"textarea","required":false}]',
'You are a professional letter writer helping a customer request a hotel booking refund. Write a formal letter citing Consumer Rights Act 2015 (services must be as described and of satisfactory quality) or Package Travel Regulations if booked as part of package, describing the issue clearly, the impact on the holiday, any additional costs incurred for alternative accommodation, and requesting full refund plus reasonable additional expenses. If booked through platform, reference their buyer protection policies.'
FROM categories WHERE slug = 'travel';

INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Travel Agency Complaint', 'travel-agency-complaint', 'Complain about poor travel agency service', 
'[{"id":"agencyName","label":"Travel Agency Name","type":"text","required":true},{"id":"bookingReference","label":"Booking Reference","type":"text","required":true},{"id":"bookingDate","label":"Booking Date","type":"date","required":true},{"id":"packageDetails","label":"Package Details","type":"textarea","required":true},{"id":"amountPaid","label":"Amount Paid","type":"text","required":true},{"id":"complaint","label":"Complaint Description","type":"textarea","required":true},{"id":"expectedVsActual","label":"What Was Promised vs What Was Delivered","type":"textarea","required":true},{"id":"remedySought","label":"Remedy Sought","type":"textarea","required":true}]',
'You are a professional letter writer helping a customer complain to a travel agency. Write a formal letter citing Package Travel and Linked Travel Arrangements Regulations 2018, describing what was promised in the package vs what was actually provided, explaining the failures and impact on holiday, and requesting appropriate remedy (partial refund, compensation, apology). If significant failure, request substantial compensation. Warn of escalation to ABTA/ATOL or Trading Standards if not resolved.'
FROM categories WHERE slug = 'travel';

-- DVLA Templates
INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Correct Incorrect Details', 'correct-dvla-details', 'Request correction of incorrect DVLA records', 
'[{"id":"yourName","label":"Your Full Name","type":"text","required":true},{"id":"driverNumber","label":"Driver Number","type":"text","required":true},{"id":"address","label":"Your Address","type":"textarea","required":true},{"id":"incorrectDetail","label":"Incorrect Detail on Record","type":"textarea","required":true},{"id":"correctDetail","label":"Correct Detail","type":"textarea","required":true},{"id":"evidence","label":"Evidence to Support Correction","type":"textarea","required":true}]',
'You are a professional letter writer helping someone request correction of DVLA records. Write a formal letter clearly stating which detail is incorrect, what it should be, providing evidence (birth certificate, passport, proof of address, etc.), and requesting prompt correction. Reference the impact of incorrect records (insurance, identification, fines sent to wrong address) and request written confirmation when corrected.'
FROM categories WHERE slug = 'dvla';

INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Appeal a DVLA Fine', 'appeal-dvla-fine', 'Appeal an unfair DVLA penalty', 
'[{"id":"yourName","label":"Your Full Name","type":"text","required":true},{"id":"vehicleReg","label":"Vehicle Registration","type":"text","required":true},{"id":"penaltyReference","label":"Penalty Reference Number","type":"text","required":true},{"id":"penaltyDate","label":"Penalty Date","type":"date","required":true},{"id":"penaltyReason","label":"Reason for Penalty","type":"textarea","required":true},{"id":"appealGrounds","label":"Grounds for Appeal","type":"textarea","required":true},{"id":"evidence","label":"Evidence to Support Appeal","type":"textarea","required":true}]',
'You are a professional letter writer helping someone appeal a DVLA fine. Write a formal appeal letter clearly stating the penalty details, explaining why it is unfair or incorrect (not the registered keeper, vehicle sold, tax was valid, notification not received, exceptional circumstances), providing evidence, and requesting cancellation of the penalty. Be factual and provide clear evidence. Request review by independent adjudicator if initial appeal rejected.'
FROM categories WHERE slug = 'dvla';

INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Lost V5C Replacement Request', 'lost-v5c-replacement', 'Request replacement V5C logbook', 
'[{"id":"yourName","label":"Your Full Name","type":"text","required":true},{"id":"address","label":"Your Address","type":"textarea","required":true},{"id":"vehicleReg","label":"Vehicle Registration","type":"text","required":true},{"id":"vehicleMake","label":"Vehicle Make/Model","type":"text","required":true},{"id":"whenLost","label":"When Was V5C Lost/Damaged","type":"date","required":true},{"id":"circumstances","label":"Circumstances of Loss","type":"textarea","required":false}]',
'You are a professional letter writer helping someone request a replacement V5C. Write a brief formal letter requesting a replacement V5C logbook, providing vehicle details and confirming your identity and address as registered keeper, explaining the V5C was lost/damaged/destroyed, and requesting the replacement be sent securely. Note that application form V62 and fee will be submitted alongside if required.'
FROM categories WHERE slug = 'dvla';

INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Incorrectly Registered Keeper Dispute', 'incorrect-keeper-dispute', 'Dispute being registered as keeper when you''re not', 
'[{"id":"yourName","label":"Your Full Name","type":"text","required":true},{"id":"yourAddress","label":"Your Address","type":"textarea","required":true},{"id":"vehicleReg","label":"Vehicle Registration","type":"text","required":true},{"id":"penaltyNotice","label":"Penalty/Notice Reference (if received)","type":"text","required":false},{"id":"explanation","label":"Explanation of Why You Are Not the Keeper","type":"textarea","required":true},{"id":"actualKeeper","label":"Actual Keeper Details (if known)","type":"textarea","required":false},{"id":"evidence","label":"Evidence You Are Not the Keeper","type":"textarea","required":true}]',
'You are a professional letter writer helping someone dispute being incorrectly registered as a vehicle keeper. Write a formal letter clearly stating you are not and have never been the registered keeper of the specified vehicle, explaining how the error may have occurred (vehicle sold, never owned, identity theft, clerical error), providing evidence (sale receipt, V5C showing previous sale, proof you owned different vehicle, etc.), and requesting immediate correction of records and cancellation of any penalties issued. Request confirmation in writing.'
FROM categories WHERE slug = 'dvla';

-- General Complaint Letters Templates
INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Company/Service Complaint', 'company-service-complaint', 'General complaint letter to any company', 
'[{"id":"companyName","label":"Company Name","type":"text","required":true},{"id":"companyAddress","label":"Company Address","type":"textarea","required":false},{"id":"accountNumber","label":"Account/Reference Number","type":"text","required":false},{"id":"dateOfIssue","label":"Date of Issue","type":"date","required":true},{"id":"complaintDescription","label":"Complaint Description","type":"textarea","required":true},{"id":"previousContact","label":"Previous Contact Attempts","type":"textarea","required":false},{"id":"impact","label":"Impact on You","type":"textarea","required":true},{"id":"remedySought","label":"Resolution Sought","type":"textarea","required":true}]',
'You are a professional letter writer helping a customer make a formal complaint. Write a professional, firm letter describing the issue clearly and factually, explaining the impact, referencing any previous contact attempts, citing relevant consumer rights (Consumer Rights Act 2015, Consumer Contracts Regulations, etc.), requesting specific remedy with reasonable deadline, and warning of escalation to Ombudsman/Trading Standards/social media if not resolved. Keep tone professional but assertive.'
FROM categories WHERE slug = 'general-complaints';

INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Billing Error', 'billing-error', 'Challenge incorrect billing or charges', 
'[{"id":"companyName","label":"Company Name","type":"text","required":true},{"id":"accountNumber","label":"Account Number","type":"text","required":true},{"id":"invoiceNumber","label":"Invoice/Bill Number","type":"text","required":false},{"id":"billDate","label":"Bill Date","type":"date","required":true},{"id":"incorrectAmount","label":"Incorrect Amount Charged","type":"text","required":true},{"id":"correctAmount","label":"Correct Amount (if known)","type":"text","required":false},{"id":"errorDescription","label":"Description of Error","type":"textarea","required":true},{"id":"evidence","label":"Evidence of Correct Amount","type":"textarea","required":false}]',
'You are a professional letter writer helping a customer challenge a billing error. Write a formal letter clearly identifying the bill/invoice, explaining the error (overcharge, duplicate charge, wrong rate, unauthorized charges), providing evidence where available (previous bills, contract terms, meter readings, etc.), requesting correction, refund of overcharged amount, and confirmation in writing. Request freeze on account if threatening disconnection. Set clear deadline for response.'
FROM categories WHERE slug = 'general-complaints';

INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Contract Breach', 'contract-breach', 'Challenge breach of contract by company', 
'[{"id":"companyName","label":"Company Name","type":"text","required":true},{"id":"contractDate","label":"Contract Date","type":"date","required":true},{"id":"contractType","label":"Type of Contract","type":"text","required":true},{"id":"breachDescription","label":"Breach Description","type":"textarea","required":true},{"id":"contractTerms","label":"Relevant Contract Terms","type":"textarea","required":true},{"id":"impact","label":"Impact of Breach","type":"textarea","required":true},{"id":"remedySought","label":"Remedy Sought","type":"select","options":["Contract performance","Compensation","Contract termination without penalty","Refund"],"required":true}]',
'You are a professional letter writer helping a customer challenge a contract breach. Write a formal letter citing specific contract clauses that have been breached, explaining how the company failed to meet obligations, the impact on the customer, citing contract law and consumer rights, and requesting specific remedy (performance, compensation, termination, refund). Set reasonable deadline and warn of legal action or ombudsman escalation if not resolved.'
FROM categories WHERE slug = 'general-complaints';

INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Misleading Advertising', 'misleading-advertising', 'Complain about false or misleading advertising', 
'[{"id":"companyName","label":"Company Name","type":"text","required":true},{"id":"productService","label":"Product/Service Advertised","type":"text","required":true},{"id":"whereAdvertised","label":"Where Was It Advertised","type":"text","required":true},{"id":"advertisementDate","label":"Advertisement Date (approx)","type":"date","required":false},{"id":"whatClaimed","label":"What Was Claimed in Ad","type":"textarea","required":true},{"id":"actualReality","label":"Actual Reality","type":"textarea","required":true},{"id":"evidence","label":"Evidence of Advertisement","type":"textarea","required":true},{"id":"actionTaken","label":"Action Taken Based on Ad","type":"textarea","required":true}]',
'You are a professional letter writer helping a customer complain about misleading advertising. Write a formal letter citing Consumer Protection from Unfair Trading Regulations 2008 and Advertising Standards Authority codes, comparing what was advertised vs reality, explaining how the advertisement was misleading or false, describing action taken based on the false claims, and requesting either refund, compensation, or contract cancellation without penalty. Warn of reports to Trading Standards and ASA if not resolved.'
FROM categories WHERE slug = 'general-complaints';

INSERT INTO templates (category_id, name, slug, description, questions, system_prompt)
SELECT id, 'Poor Customer Service', 'poor-customer-service', 'Complain about unacceptable customer service', 
'[{"id":"companyName","label":"Company Name","type":"text","required":true},{"id":"incidentDate","label":"Incident Date","type":"date","required":true},{"id":"location","label":"Location/Branch (if applicable)","type":"text","required":false},{"id":"staffInvolved","label":"Staff Members Involved (if known)","type":"text","required":false},{"id":"incidentDescription","label":"Incident Description","type":"textarea","required":true},{"id":"impact","label":"Impact on You","type":"textarea","required":true},{"id":"remedySought","label":"What You Want the Company to Do","type":"textarea","required":true}]',
'You are a professional letter writer helping a customer complain about poor customer service. Write a firm but professional letter describing the specific incident(s) of poor service (rudeness, discrimination, incompetence, ignoring concerns), explaining the impact and distress caused, expressing disappointment, and requesting: apology, staff training/action, compensation/goodwill gesture, and assurance it won''t recur. Reference any discrimination laws if relevant (Equality Act 2010). Warn of social media review and ombudsman escalation if not resolved satisfactorily.'
FROM categories WHERE slug = 'general-complaints';
